services:
  - type: web
    name: lingwolamki
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn base.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
      - key: DEBUG
        value: 'False'
      - key: USE_MYSQL
        value: 'False'